apiVersion: v1
kind: Service
metadata:
         name: mongo-express-service  #a random name
spec:
  selector: 
    app: mongo-express # to connect to pod through label
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081 #service port, can be different from target port
      targetport: 8081 #containerport of Deployment, gotten from the image
      NodePort: 31000
